In [2]:
import numpy as np
from itertools import zip_longest

def split_k_folds(k_folds, X, y, groups):
    n = groups[-1]
    groups_indices = np.zeros(shape=(self.n, ), dtype=np.int64)
    groups_indices[1:] = np.where(groups[:-1] != groups[1:])[0]
    
    indx = np.empty(shape=k_folds, dtype=np.int32)
    indx.fill(n//k_folds)
    indx[-n%k_folds:] += 1
    indx.cumsum()
    
    for a, b in zip(indx - indx[0], indx):
        yield (X_train[b:a:-1], y_train[b:a:-1],
               X_train[a:b], y_train[a:b])
        

In [50]:
a = np.ones(shape=(1000, )).cumsum()
a

array([   1.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,    9.,
         10.,   11.,   12.,   13.,   14.,   15.,   16.,   17.,   18.,
         19.,   20.,   21.,   22.,   23.,   24.,   25.,   26.,   27.,
         28.,   29.,   30.,   31.,   32.,   33.,   34.,   35.,   36.,
         37.,   38.,   39.,   40.,   41.,   42.,   43.,   44.,   45.,
         46.,   47.,   48.,   49.,   50.,   51.,   52.,   53.,   54.,
         55.,   56.,   57.,   58.,   59.,   60.,   61.,   62.,   63.,
         64.,   65.,   66.,   67.,   68.,   69.,   70.,   71.,   72.,
         73.,   74.,   75.,   76.,   77.,   78.,   79.,   80.,   81.,
         82.,   83.,   84.,   85.,   86.,   87.,   88.,   89.,   90.,
         91.,   92.,   93.,   94.,   95.,   96.,   97.,   98.,   99.,
        100.,  101.,  102.,  103.,  104.,  105.,  106.,  107.,  108.,
        109.,  110.,  111.,  112.,  113.,  114.,  115.,  116.,  117.,
        118.,  119.,  120.,  121.,  122.,  123.,  124.,  125.,  126.,
        127.,  128.,

In [19]:
b = np.array((1,4,3))
a[b, 1]

array([102., 105., 104.])

In [23]:
type(np.where(a < 5)[0])

numpy.ndarray

In [27]:
k_folds = 3
n = 10
indx = np.zeros(shape=k_folds + 1, dtype=np.int32)
indx[1:] = (n//k_folds)
indx[-(n%k_folds):] += 1
indx, indx.cumsum()

(array([0, 3, 3, 4], dtype=int32), array([ 0,  3,  6, 10]))

In [28]:
a = np.array([1.3, 1.7, 1.5, 1.2, 1.9])

In [29]:
a

array([1.3, 1.7, 1.5, 1.2, 1.9])

In [31]:
np.around(a)

array([1., 2., 2., 1., 2.])

In [39]:
a[3:7]

array([4., 5., 6., 7.])

In [45]:
a[-3:3:1]

array([], dtype=float64)

In [48]:
a[slice(-3,3,1)]

array([], dtype=float64)

In [61]:
%%timeit
a[np.arange(-123,283)]

2.14 µs ± 357 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [62]:
%%timeit
np.hstack((a[-123:], a[:283]))

4.79 µs ± 444 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [59]:
(a[np.arange(-123, 283)] != np.hstack((a[-123:], a[:283]))).sum()

0

In [63]:
a = np.array([5,6,2,9,4])
b = np.append(a, 1010)
a[1] = -10000
b[2] = 1010100101
a, b

(array([     5, -10000,      2,      9,      4]),
 array([         5,          6, 1010100101,          9,          4,
              1010]))

In [ ]:
np.array[]